tensorboard:
  _target_: lightning.pytorch.loggers.tensorboard.TensorBoardLogger
  save_dir: "${hydra:runtime.cwd}/logs/tensorboard/"
  name: null
  log_graph: False
  default_hp_metric: True
  prefix: ""
