# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - hydra: default
  - data: mnist
  - loggers: default
  - trainer: default
  - callbacks: default
  - model: mnist
# task name, determines output directory path
task_name: "train"
# pass a checkpoint path to resume training from a saved checkpoint
# checkpoint: ${hydra:runtime.cwd}/models/last.ckpt
# seed for random number generators in pytorch, numpy and python.random
seed: 1234
# evaluate on test set, using best model weights achieved during training
# lightning chooses best weights based on the metric specified in checkpoint callback
test: True
